---
title: "R Notebook"
output: html_notebook
---

# Assignment 1

```{r}
library(dplyr)
library(tidyr)
library(reshape2)
library(ggplot2)
```

<!-- Insert Chunk: *Ctrl+Alt+I* -->
<!-- Knit-Preview: *Ctrl+Alt+K* -->

```{r}
keyPressDataWithLaneDeviation = read.csv("./keyPressDataWithLaneDeviation.csv")
head(keyPressDataWithLaneDeviation)
# se <- function(x) {
#   return(sqrt(var(x) / length(x)))
# }
se <- function(x) sd(x)/sqrt(length(x))
```



### Question 1A
```{r}
subsetted_data <- subset(keyPressDataWithLaneDeviation, typingErrorMadeOnTrial == 0)
subsetted_data <- subsetted_data[subsetted_data$phoneNrLengthAfterKeyPress==11,]
subsetted_data <- subset(subsetted_data, (partOfExperiment == "dualSteerFocus" | partOfExperiment == "dualDialFocus"))
# subsetted_data = subset(subsetted_data, partOfExperiment == c("dualDialFocus", "dualSteerFocus"))
head(subsetted_data)
```

```{r}
aggregated_data <- aggregate(timeRelativeToTrialStart ~ pp + partOfExperiment, subsetted_data, FUN = mean)
head(aggregated_data)
```
```{r}
grand_mean <- aggregate(timeRelativeToTrialStart ~ partOfExperiment, aggregated_data, FUN = mean)
grand_standard_deviation <- aggregate(timeRelativeToTrialStart ~ partOfExperiment, aggregated_data, FUN = sd)
grand_standard_error <- aggregate(timeRelativeToTrialStart ~ partOfExperiment, aggregated_data, FUN = se)
final_stats <- data.frame(cbind(grand_mean$timeRelativeToTrialStart, grand_standard_deviation$timeRelativeToTrialStart, grand_standard_error$timeRelativeToTrialStart))
colnames(final_stats) <- c("means", "std", "se")
results_question_a = round(final_stats / 1000, digits = 2)
# results_question_a
row.names(results_question_a) <- c("Dual Dial Focus", "Dual Steer Focus")
results_question_a

```
### Question 1B
```{r}
subsetted_data <- subset(keyPressDataWithLaneDeviation, typingErrorMadeOnTrial == 0)
subsetted_data <- subset(subsetted_data, (partOfExperiment == "dualSteerFocus" | partOfExperiment == "dualDialFocus"))
# subsetted_data <- subset(subsetted_data, Event1 == "Keypress")
aggregated_data <- aggregate(lanePosition ~ pp + partOfExperiment, subsetted_data, FUN = function(x) mean(abs(x)))
head(aggregated_data)
```


```{r}
grand_mean <- aggregate(lanePosition ~ partOfExperiment, aggregated_data, FUN = mean)
grand_standard_deviation <- aggregate(lanePosition ~ partOfExperiment, aggregated_data, FUN = sd)
grand_standard_error <- aggregate(lanePosition ~ partOfExperiment, aggregated_data, FUN = se)
final_stats <- data.frame(cbind(grand_mean$lanePosition, grand_standard_deviation$lanePosition, grand_standard_error$lanePosition))
colnames(final_stats) <- c("means", "std", "se")
results_question_1b = round(final_stats, digits = 2)
row.names(results_question_1b) <- c("Dual Dial Focus", "Dual Steer Focus")
results_question_1b
# reshaped_aggregated_data = dcast(aggregated_data, pp + partOfExperiment  ~ phoneNrLengthAfterKeyPress)
# reshaped_aggregated_data
```
### Question 1C

```{r}
subsetted_data <- subset(keyPressDataWithLaneDeviation, typingErrorMadeOnTrial == 0)
subsetted_data <- subset(subsetted_data, Event1 == "Keypress")
subsetted_data <- subset(subsetted_data, (partOfExperiment == "dualSteerFocus" | partOfExperiment == "dualDialFocus"))
subsetted_data$absLanePosition <- abs(subsetted_data$lanePosition)
subsetted_data$partOfExperiment <- factor(subsetted_data$partOfExperiment)
subsetted_data$timeRelativeToTrialStart <- round(subsetted_data$timeRelativeToTrialStart/1000, 2)

per_key_and_participant_data <- subsetted_data %>% group_by(pp, phoneNrLengthAfterKeyPress, partOfExperiment) %>% summarise("adjMeanTime"=mean(timeRelativeToTrialStart), "adjMeanLanePosition"=mean(absLanePosition))
per_key_data <- per_key_and_participant_data %>% group_by(phoneNrLengthAfterKeyPress, partOfExperiment) %>% summarise("meanTime"=mean(adjMeanTime), "meanLanePosition"=mean(adjMeanLanePosition), "seLanePosition"=round(se(adjMeanLanePosition),2))
per_key_data$partOfExperiment = factor(per_key_data$partOfExperiment)

mlegend = guide_legend(title="Trial Conditions")
ggplot(data = per_key_data,  aes(x = meanTime, y = meanLanePosition, colour = partOfExperiment), group=partOfExperiment) +
  geom_point(aes(shape=partOfExperiment), size=3) +
  geom_errorbar(aes(ymin=meanLanePosition-seLanePosition, ymax=meanLanePosition+seLanePosition), width=.1) +
  guides(colour=mlegend,shape=mlegend) + 
  labs(x="Dialing Time (sec)", y="Lateral Deviation (m)", title="Vehicle Lateral Deviation between consecutive keypresses\nunder varying Dual-task Performance Objectives")+
  geom_line() 

```
### Question 1D

TODO: EVA



