---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(tidyr)
library(reshape2)
library(ggplot2)
library(gridExtra)
```

# Assignment 1

```{r}
se <- function(x) sd(x)/sqrt(length(x))
keyPressDataWithLaneDeviation = read.csv("./keyPressDataWithLaneDeviation.csv")
tabledrift <- read.csv("tableOfDriftValuesCalibration.csv")
tabledrift$trialTime = round(tabledrift$trialTime/1000, 2)
tabledrift$trial = factor(tabledrift$trial)
head(tabledrift)
```


### Question 3A

```{r}
filtered_data = keyPressDataWithLaneDeviation %>% filter(partOfExperiment == "singleDialing2") %>% filter(typingErrorMadeOnTrial==0) %>% filter(Event1 == "Keypress")
 head(filtered_data)
```

```{r}
filtered_data$diffs = 0
filtered_data$diffs[2:nrow(filtered_data)] = diff(filtered_data$timeRelativeToTrialStart)
filtered_data$diffs[filtered_data$phoneNrLengthBeforeKeyPress == 0] = filtered_data$timeRelativeToTrialStart[filtered_data$phoneNrLengthBeforeKeyPress == 0]
head(filtered_data)

```

```{r}
per_participant_per_key_data <- filtered_data %>% group_by(pp, trial, phoneNrLengthBeforeKeyPress) %>% summarise("adjMeanDiffs"=mean(diffs))
head(per_participant_per_key_data)
```

```{r}
tmp <- per_participant_per_key_data %>% group_by(pp, phoneNrLengthBeforeKeyPress) %>% summarise("adjMeanDiffs"=mean(adjMeanDiffs))
head(tmp)
```


```{r}
per_key_data <- tmp %>% group_by(pp) %>% summarise("adjMeanDiffs"=mean(adjMeanDiffs))
head(per_key_data)
```
```{r}
per_key_wo_zeros = per_key_data[1:nrow(per_key_data),]$adjMeanDiffs
average_key_press_intervall <- round(mean(per_key_wo_zeros), 2)
average_key_press_intervall
```
# Question 3B

We pick 264 by rounding up the calculated interkeypress. This is the average across all participants and therefore, a valid estimation of the parameter. 

